#!/bin/bash

#module load compilers/gnu/7.3
#module load libraries/blas/3.8.0-intel2018-7.3
#module load libraries/lapack/3.8.0-gnu-7.3
#module load libraries/gsl/2.1-gnu-5.3

module load /home/sw/modules/gcc-7.4.0

g++ -lblas -llapack -lgslcblas -lgsl -std=gnu++14 ../pdm.cpp -o ../pdm
echo -e "----- COMPILATION DONE -----"
