#!/bin/bash

##module load compilers/gnu/7.3 

##module load compilers/intel/2018.2.199
##eval $loadIntelLibs

##module load libraries/mkl/intel-2018.2.199
##eval $loadIntelMkl

##module load libraries/blas/3.8.0-intel2018-7.3

##module load libraries/lapack/3.8.0-intel2018-7.3 

##module load libraries/gsl/2.1-gnu-5.3

source /home/sw/masternode/intel/2015/install/composerxe/bin/compilervars.sh intel64
module load /home/sw/modules/gcc-7.4.0

icc -mkl -lblas -llapack -lgslcblas -lgsl pdm.cpp
echo -e "----- COMPILATION DONE -----"
