#!/bin/bash

module load /home/sw/modules/gcc-7.4.0

CPP=g++
SOURCE='../omp/pdm_omp.cpp'
EXEC='../omp/pdm_omp'
LDFLAGS='-lblas -llapack -lgslcblas -lgsl -std=gnu++14'
OMP='-fopenmp'

$CPP $LDFLAGS $OMP $SOURCE -o $EXEC
echo "$CPP $LDFLAGS $OMP $SOURCE -o $EXEC"
echo -e "----- COMPILATION DONE -----"
